/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DEV STUDIOS 3D (https://sketchfab.com/devraj.nunnu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/symbiote-spiderman-tobey-maguire-b95e7b8f860748089b7784525a3e340a
Title: Symbiote Spiderman - Tobey Maguire
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/native";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Object_66: THREE.SkinnedMesh;
		Object_69: THREE.SkinnedMesh;
		Object_72: THREE.SkinnedMesh;
		Object_75: THREE.SkinnedMesh;
		Object_78: THREE.SkinnedMesh;
		Object_81: THREE.SkinnedMesh;
		Object_84: THREE.SkinnedMesh;
		Object_87: THREE.SkinnedMesh;
		GLTF_created_0_rootJoint: THREE.Bone;
	};
	materials: {
		LensInside: THREE.MeshStandardMaterial;
		Webbing: THREE.MeshStandardMaterial;
		material: THREE.MeshPhysicalMaterial;
		Blue: THREE.MeshStandardMaterial;
		Back_Logo: THREE.MeshStandardMaterial;
		Front_Logo: THREE.MeshStandardMaterial;
		Lenses: THREE.MeshStandardMaterial;
	};
};

export function Spiderman(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		require("../assets/model/Spiderman.glb")
	) as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, 0]} scale={0.002}>
				<group position={[-0.025, 33.974, -3.714]} rotation={[-1.57, 0, 0]}>
					<group
						position={[-0.004, 1595.176, -32.616]}
						rotation={[Math.PI / 2, 0, 0]}>
						<primitive object={nodes.GLTF_created_0_rootJoint} />
						<skinnedMesh
							geometry={nodes.Object_66.geometry}
							material={materials.LensInside}
							skeleton={nodes.Object_66.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_69.geometry}
							material={materials.Webbing}
							skeleton={nodes.Object_69.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_72.geometry}
							material={materials.Webbing}
							skeleton={nodes.Object_72.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_75.geometry}
							material={materials.material}
							skeleton={nodes.Object_75.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_78.geometry}
							material={materials.Blue}
							skeleton={nodes.Object_78.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_81.geometry}
							material={materials.Back_Logo}
							skeleton={nodes.Object_81.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_84.geometry}
							material={materials.Front_Logo}
							skeleton={nodes.Object_84.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_87.geometry}
							material={materials.Lenses}
							skeleton={nodes.Object_87.skeleton}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}
